#pragma once

#include <iostream>
#include <fstream>
#include <iomanip>
#include <thread>
#include <sstream>
#include "CRCpp/inc/CRC.h"
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <SFML/System.hpp>
#include "types.hxx"
#include "version.hxx"
#include "structs.hxx"
#include "savescrn.hxx"
#include "title.hxx"
#include "jukebox.hxx"
#include "utils.hxx"
#include "prefs.hxx"
#include "game.hxx"
#include "collision.hxx"